ALTER TABLE payment_cards
ADD COLUMN daily_limit DECIMAL(10,2) NOT NULL DEFAULT 0.00,
ADD COLUMN monthly_limit DECIMAL(10,2) NOT NULL DEFAULT 0.00,
ADD COLUMN daily_txn_limit INT NOT NULL DEFAULT 0,
ADD COLUMN monthly_txn_limit INT NOT NULL DEFAULT 0;
